### ISSUE TITLE
Installing TaskPaper Extended Notes for alfred workflow

### ISSUE THREAD

**Issue by nicwhitts** [pslobo/Scripts#6]
Im trying to use your script, you provide the file .alfredextension But i cannot find anywhere how to use this?

I managed to scrape google to find a file with .alfedworkflow but is causing error in the apple script.

How can i use this (alfred3 TaskPaper 3)? Would really love to have this functionality

**Comment by pslobo** [comment]
Hey Nic,

This script was initially written for TaskPaper 2 and Alfred 2 so it won't work with TaskPaper 3 since much has changed under the hood.

I'm a little strapped for time so I won't be fixing this any time soon, but hopefully I'll get around to it someday. Sorry that I don't have better news for you here.

Maybe check out @ttscoff's [version](https://github.com/ttscoff/ExtraInfoPlus) (which is much better in fact better but I'm not sure if he's update either).

**Comment by nicwhitts** [comment]
Thanks for responding, i assumed that much.

I found a similar program for Sublime Text: PlainTasks
https://github.com/aziz/PlainTasks

It seems to be able to open files, so il give this a go
